ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS contents ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS homeworks ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS homework_questions ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS questions ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT false;