ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS deleted;
ALTER TABLE IF EXISTS contents DROP COLUMN IF EXISTS deleted;
ALTER TABLE IF EXISTS homeworks DROP COLUMN IF EXISTS deleted;
ALTER TABLE IF EXISTS homework_questions DROP COLUMN IF EXISTS deleted;
ALTER TABLE IF EXISTS questions DROP COLUMN IF EXISTS deleted;