// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels(in *jlexer.Lexer, out *User) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id":
			out.ID = int64(in.Int64())
		case "Name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels(out *jwriter.Writer, in User) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v User) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v User) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *User) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *User) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels(l, v)
}
func easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels1(in *jlexer.Lexer, out *Question) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id":
			out.ID = int64(in.Int64())
		case "Name":
			out.Name = string(in.String())
		case "Content_Id":
			out.ContentID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels1(out *jwriter.Writer, in Question) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Content_Id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ContentID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Question) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Question) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Question) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Question) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels1(l, v)
}
func easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels2(in *jlexer.Lexer, out *HomeworkQuestion) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id":
			out.ID = int64(in.Int64())
		case "Homework_Id":
			out.HomeworkID = int64(in.Int64())
		case "Question_Id":
			out.QuestionID = int64(in.Int64())
		case "Order":
			out.Order = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels2(out *jwriter.Writer, in HomeworkQuestion) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"Homework_Id\":"
		out.RawString(prefix)
		out.Int64(int64(in.HomeworkID))
	}
	{
		const prefix string = ",\"Question_Id\":"
		out.RawString(prefix)
		out.Int64(int64(in.QuestionID))
	}
	{
		const prefix string = ",\"Order\":"
		out.RawString(prefix)
		out.Int64(int64(in.Order))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HomeworkQuestion) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HomeworkQuestion) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HomeworkQuestion) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HomeworkQuestion) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels2(l, v)
}
func easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels3(in *jlexer.Lexer, out *Homework) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id":
			out.ID = int64(in.Int64())
		case "Name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels3(out *jwriter.Writer, in Homework) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Homework) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Homework) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Homework) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Homework) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels3(l, v)
}
func easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels4(in *jlexer.Lexer, out *Content) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id":
			out.ID = int64(in.Int64())
		case "Task":
			if in.IsNull() {
				in.Skip()
				out.Task = nil
			} else {
				if out.Task == nil {
					out.Task = new(string)
				}
				*out.Task = string(in.String())
			}
		case "Answer":
			if in.IsNull() {
				in.Skip()
				out.Answer = nil
			} else {
				if out.Answer == nil {
					out.Answer = new(string)
				}
				*out.Answer = string(in.String())
			}
		case "Solution":
			if in.IsNull() {
				in.Skip()
				out.Solution = nil
			} else {
				if out.Solution == nil {
					out.Solution = new(string)
				}
				*out.Solution = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels4(out *jwriter.Writer, in Content) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"Task\":"
		out.RawString(prefix)
		if in.Task == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Task))
		}
	}
	{
		const prefix string = ",\"Answer\":"
		out.RawString(prefix)
		if in.Answer == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Answer))
		}
	}
	{
		const prefix string = ",\"Solution\":"
		out.RawString(prefix)
		if in.Solution == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Solution))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Content) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Content) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB109ec67EncodeGithubComErupshisRevtrackerGitDbModels4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Content) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Content) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB109ec67DecodeGithubComErupshisRevtrackerGitDbModels4(l, v)
}
