basePath: /api
definitions:
  data.Content:
    properties:
      Answer:
        type: string
      Solution:
        type: string
      Task:
        type: string
    type: object
  data.Data:
    properties:
      Homework:
        $ref: '#/definitions/data.HomeworkData'
    type: object
  data.Homework:
    properties:
      Id:
        type: integer
      Name:
        type: string
    type: object
  data.HomeworkData:
    properties:
      Id:
        type: integer
      Name:
        type: string
      Questions:
        items:
          $ref: '#/definitions/data.Question'
        type: array
    type: object
  data.HomeworkQuestion:
    properties:
      Homework_Id:
        type: integer
      Id:
        type: integer
      Order:
        type: integer
      Question_Id:
        type: integer
    type: object
  data.Question:
    properties:
      Content:
        $ref: '#/definitions/data.Content'
      Id:
        type: integer
      Name:
        type: string
    type: object
  data.User:
    properties:
      Login:
        type: string
      Name:
        type: string
      Password:
        type: string
    type: object
info:
  contact:
    email: e.rupshis@gmail.com
    name: erupshis
  description: Swagger API for rev tracker.
  termsOfService: http://swagger.io/terms/
  title: RevTracker server Swagger API
  version: "1.0"
paths:
  /data:
    post:
      consumes:
      - application/json
      description: Insert godoc
      operationId: data-insert
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/data.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Data'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: adds new homework data
      tags:
      - homework_data
  /data/{id}:
    delete:
      description: Delete godoc
      operationId: data-delete
      parameters:
      - description: homework id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: deletes existing data
      tags:
      - homework_data
    get:
      description: Select godoc
      operationId: data-select
      parameters:
      - description: homework id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Data'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: select new data
      tags:
      - homework_data
    put:
      consumes:
      - application/json
      description: Update godoc
      operationId: data-update
      parameters:
      - description: updated homework data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/data.Data'
      - description: homework id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Data'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: updates homework data
      tags:
      - homework_data
  /homework:
    post:
      consumes:
      - application/json
      description: Insert godoc
      operationId: homework-insert
      parameters:
      - description: homework config
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/data.Homework'
      produces:
      - text/plain
      responses:
        "200":
          description: 'Id: ''homework number'''
          schema:
            type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: adds new homework
      tags:
      - homework
  /homework/{id}:
    delete:
      description: Delete godoc
      operationId: homework-delete
      parameters:
      - description: homework id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: deletes existing homework
      tags:
      - homework
    get:
      description: Select godoc
      operationId: homework-select
      parameters:
      - description: homework id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Homework'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: select homework
      tags:
      - homework
    put:
      consumes:
      - application/json
      description: Update godoc
      operationId: homework-update
      parameters:
      - description: updated homework
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/data.Homework'
      - description: homework id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Homework'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: updates homework
      tags:
      - homework
  /homework_question:
    post:
      consumes:
      - application/json
      description: Insert godoc
      operationId: hw-question-insert
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/data.HomeworkQuestion'
      produces:
      - text/plain
      responses:
        "200":
          description: 'Id: ''homework question number'''
          schema:
            type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: adds new homework_question
      tags:
      - homework_question
  /homework_question/{id}:
    delete:
      description: Delete godoc
      operationId: hw-question-delete
      parameters:
      - description: homework id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: deletes existing homework_question
      tags:
      - homework_question
    get:
      description: Select godoc
      operationId: hw-question-select
      parameters:
      - description: homework question id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.HomeworkQuestion'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: select homework question
      tags:
      - homework_question
    put:
      consumes:
      - application/json
      description: Update godoc
      operationId: hw-question-update
      parameters:
      - description: updated homework question
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/data.HomeworkQuestion'
      - description: homework id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.HomeworkQuestion'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: updates homework question
      tags:
      - homework_question
  /question:
    post:
      consumes:
      - application/json
      description: Insert godoc
      operationId: question-insert
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/data.Question'
      produces:
      - text/plain
      responses:
        "200":
          description: 'Id: ''question number'''
          schema:
            type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: adds new question
      tags:
      - question
  /question/{id}:
    delete:
      description: Delete godoc
      operationId: question-delete
      parameters:
      - description: question id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: deletes existing question
      tags:
      - question
    get:
      description: Select godoc
      operationId: question-select
      parameters:
      - description: question id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Question'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: select question
      tags:
      - question
    put:
      consumes:
      - application/json
      description: Update godoc
      operationId: question-update
      parameters:
      - description: updated question
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/data.Question'
      - description: question id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Question'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: updates question
      tags:
      - question
  /user/login:
    post:
      consumes:
      - application/json
      description: Login godoc
      operationId: Login
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/data.User'
      responses:
        "200":
          description: OK
          headers:
            Authorization:
              description: Bearer {token}
              type: string
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: user authentication
      tags:
      - authentication
  /user/register:
    post:
      consumes:
      - application/json
      description: Register godoc
      operationId: Register
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/data.User'
      responses:
        "200":
          description: OK
          headers:
            Authorization:
              description: Bearer {token}
              type: string
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: new user registering
      tags:
      - authentication
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
